baseurl = "https://www.jayasinghe.de"
languageCode = "en-us"
title = "rob's website"
theme = "hugo-nes-classic"
#theme = "nes"


[menu]

    [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1

    [[menu.main]]
        name = "Articles"
        url = "/post"
        weight = 2

    [[menu.main]]
        name = "Imprint"
        url = "/page/imprint"
        weight = 3

    [[menu.main]]
        name = "Contact"
        url = "/page/contact"
        weight = 4

    [[menu.main]]
        name = "About"
        url = "/page/about"
        weight = 5
